participant: Solid1

precice-config-file: precice-config.xml

interfaces:
- mesh: Solid1-Mesh
  patches:
  - interface
  write-data: Heat-Flux
  read-data: Temperature

CHTenabled: true
evaluateBoundaries: false
